import tees from '../../assets/images/black_tees.jpg';

export const products = [
    {
        _id: 1,
        name: 'Red Plaid Shirt',
        shortDesc: 'Classic red plaid shirt for a casual look',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['S', 'M', 'L', 'XL'],
        price: 499,
        imgUrl: tees,
        stock: 18,
        category: 'tees',
        trending: true,
    },
    {
        _id: 2,
        name: 'Denim Jacket',
        shortDesc: 'Stylish denim jacket with a modern fit',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['M', 'L', 'XL'],
        price: 499,
        imgUrl: tees,
        stock: 10,
        category: 'hoodies',
        trending: false,
    },
    {
        _id: 3,
        name: 'Black Leather Boots',
        shortDesc: 'Durable black leather boots for all occasions',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['8', '9', '10', '11'],
        price: 499,
        imgUrl: tees,
        stock: 15,
        category: 'tees',
        trending: true,
    },
    {
        _id: 4,
        name: 'Green Hoodie',
        shortDesc: 'Comfortable green hoodie for a cozy day',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['S', 'M', 'L'],
        price: 499,
        imgUrl: tees,
        stock: 22,
        category: 'hoodies',
        trending: true,
    },
    {
        _id: 5,
        name: 'Striped Polo Shirt',
        shortDesc: 'Elegant striped polo shirt for a refined look',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['M', 'L', 'XL'],
        price: 499,
        imgUrl: tees,
        stock: 14,
        category: 'tees',
        trending: false,
    },
    {
        _id: 6,
        name: 'Khaki Chinos',
        shortDesc: 'Versatile khaki chinos for a polished outfit',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['30', '32', '34', '36'],
        price: 499,
        imgUrl: tees,
        stock: 25,
        category: 'pants',
        trending: true,
    },
    {
        _id: 7,
        name: 'Blue Crewneck Sweater',
        shortDesc: 'Warm blue crewneck sweater for chilly days',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['S', 'M', 'L'],
        price: 499,
        imgUrl: tees,
        stock: 18,
        category: 'sweaters',
        trending: false,
    },
    {
        _id: 8,
        name: 'Printed Summer Dress',
        shortDesc: 'Colorful printed summer dress for a vibrant look',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['XS', 'S', 'M'],
        price: 499,
        imgUrl: tees,
        stock: 30,
        category: 'tees',
        trending: true,
    },
    {
        _id: 9,
        name: 'Brown Leather Belt',
        shortDesc: 'Classic brown leather belt to complete your outfit',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['32', '34', '36'],
        price: 499,
        imgUrl: tees,
        stock: 15,
        category: 'pants',
        trending: false,
    },
    {
        _id: 10,
        name: 'Grey Beanie Hat',
        shortDesc: 'Cozy grey beanie hat to keep you warm in style',
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac lectus nec nisi congue posuere.',
        size: ['One Size'],
        price: 499,
        imgUrl: tees,
        stock: 20,
        category: 'sweaters',
        trending: true,
    },
];
